test:
  name: simple
  description: FogCare benchmar for academic purposes.
  workers:
    type: local
    number: 5      #number of clients you need to spawn
  rounds:
      - label: readAsset
        description: Read patient fogcare benchmark
        txDuration: 30
        rateControl: 
          type: fixed-load
          opts:
            transactionLoad: 10
        workload:
          module: scenarios/workload.js
          arguments:
            contractId: gocc